version: '3.8'
services:
  telepinger:
    build: .
    image: telepinger
    hostname: telepinger
    container_name: telepinger
    restart: always
    environment:
      - MINUTES_INTERVAL=1
      - PING_HOST=8.8.8.8
      - PING_PACKETS=5
      - PING_INTERVAL=1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m" 
